spring:
  profiles:
    active:
    -dev
    
---
spring:
  profiles: dev   #开发环境1
  application:
    name: mycloud-config-dev
        
        
---
spring:
  profiles: test   #测试环境1
  application:
     name: mycloud-config-test
#UTF-8